source 'http://rubygems.org'

gem 'rails', '3.0.7'

gem 'devise'
gem 'cancan'
gem 'jquery-rails'
gem 'haml'
gem 'formtastic', '1.2.4'
gem 'kaminari'
gem 'compass'
gem 'compass-960-plugin'
gem 'typus', :git => 'https://github.com/fesplugas/typus.git'
gem 'ancestry'
gem 'gmaps4rails'
gem 'aws-s3'
gem "paperclip"
# Temperary test data generators
gem 'populator'
gem 'faker'
gem 'barometer'
gem 'acts-as-taggable-on'
gem 'rails3-jquery-autocomplete'
gem 'omniauth'

group :development, :test do
  gem 'hpricot'
  gem 'capybara'
  gem 'launchy'
  gem 'cucumber-rails'
  gem 'rspec-rails'
  gem 'shoulda'
  gem 'factory_girl_rails'
  gem 'mongrel', '1.2.0.pre2'
  gem 'sqlite3'
  # gem 'pg'
  gem 'ruby-debug19'
  # gem 'rb-fsevent', :require => false if RUBY_PLATFORM =~ /darwin/i
  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-sass'
  gem 'guard-bundler'
  gem 'growl'
  # gem 'guard-mozrepl'
  gem 'guard-livereload'
end
